language: common-lisp
sudo: required

env:
  global:
   - PATH=~/.roswell/bin:$PATH
   - ROSWELL_BRANCH=master
   - ROSWELL_INSTALL_DIR=$HOME/.roswell
  matrix:
    - LISP=sbcl-bin

#addons:
#  apt:
#    packages:
#      - libc6-i386

install:
  - sudo apt-get -qq update --force-yes > /dev/null
  - curl -L https://raw.githubusercontent.com/roswell/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  - ros install dexador

script:
  - openssl version
  - curl -v https://api.github.com
  - ros -s dexador -e '(let ((ctx (cl+ssl:make-context :verify-depth 10 :verify-mode cl+ssl:+ssl-verify-none+ :verify-location :default))) (cl+ssl:with-global-context (ctx) (print (dex:get "https://api.github.com"))))'
